name: Build

on:
  pull_request:
    branches:
      - "*"

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 14C
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn --frozen-lockfile
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: script download and install access-content
        run: |
         chmod +x ./scripts/getContent.sh
         ./scripts/getContent.sh $ACCESS_CONTENT_URL
        shell: bash
        env:
          ACCESS_CONTENT_URL: https://github.com/InseeFr/Coleman-Access-Content/releases/download/0.0.2/content.zip  
      - run: yarn
      - run: yarn run test
      - run: yarn build
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build
